build:
  tests:
    override:
      - pylint-run --rcfile=.pylint.ini
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - "*/tests/*"
    - "*/static/js/*min.js"
