#!/usr/bin/env bash

export PYTHONPATH=.
set -e

coverage run --omit=flaskapi/tests/runtests.py,flaskapi/tests/__init__.py --source=flaskapi flaskapi/tests/runtests.py $@
flake8 flaskapi --ignore=E128,E501 --exclude=__init__.py

if [[ ! "$@" ]] ; then
    echo
    coverage report
fi
